### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by ghost** [wenhuchen/TheoremQA#2]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/wenhuchen/TheoremQA/blob/123e36beaaa97c01f28a582f13c4f77a6822c199/run_claude.py#L18

Would love to know if this might help - https://github.com/BerriAI/litellm

~100 lines of code, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by ghost** [comment]
cc: @wenhuchen

**Comment by wenhuchen** [comment]
The library looks great! It could save lots of effort to maintain these API calls. I will look into this!

**Comment by ishaan-jaff** [comment]
@wenhuchen Happy to make a PR to help with the integration

**Comment by wenhuchen** [comment]
Sure, that would be great! Make sure to create a new script with litellm library.
