### ISSUE TITLE
Whether the golden programs available?

### ISSUE THREAD

**Issue by qshi95** [wenhuchen/TheoremQA#4]
Thanks for the excellent work! I'd like to know if the golden program for each question is available. Since the questions in TheoremQA are a little difficult for people without expert knowledge. Thanks a lot!

**Comment by qshi95** [comment]
Already noticed the PoT rationales of TheoremQA are annotated by GPT4 in your new work. Issue closed.

**Comment by wenhuchen** [comment]
You can find these rationale in my solution/ folder, or under the outputs/ folder.
